server:
  port: ${PORT:5000}
eureka:
  instance:
    hostname: local
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  password: ${EUREKA_USER_PASSWORD:password}
spring:
  security:
    user:
      password: ${EUREKA_USER_PASSWORD:password}
